version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: twodo-database
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin123
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: